### ISSUE TITLE
How to modify the adapt to used in serial  communication.TKS!

### ISSUE THREAD

**Issue by skylin008** [peterhinch/Micropython-scheduler#2]

**Comment by peterhinch** [comment]
It shouldn't need modification. On the assumption that you're using a Pyboard, I would create two threads, one for tx and the other for rx. There would be a tx queue and an rx queue (implemented as lists). Other threads would populate the tx queue (append) and remove strings from the rx queue (pop(0)) as they become available.

The tx thread would loop forever checking if there are strings queued. If there are, it would pop(0) to get the oldest, transmit it, and loop until all bytes were written (remembering to yield in each loop) before reverting to the outer loop.

The rx thread is slightly more tricky. You don't want a timeout as it would lock the scheduler for the duration so you need to loop on any() and only read characters up to the number present, appending them to a temporary string. How you append data to the rx queue depends on the nature of the data. Fixed length records are easy. Otherwise if your data is in lines, you need to check for an end of line character and break the incoming data accordingly.

All manageable with care. I've just written something similar, but not using the UART so I can't offer any actual code.
